version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./etc/prometheus.yml:/etc/prometheus/prometheus.yml"
  counter1:
    build: "counter"
    user: "node"
    command: "npm start"
  counter2:
    build: "counter"
    user: "node"
    command: "npm start"
