global:
  scrape_interval: 1s
  evaluation_interval: 30s

scrape_configs:
  - job_name: counter
    static_configs:
      - targets:
          - "counter1:8081"
          - "counter2:8081"
        labels:
          app: counter

